export const SET_DATA__CONTENT = 'SET_DATA__CONTENT';
export const TOGGLE__LIST__ACTIVE = 'TOGGLE__LIST__ACTIVE';
export const TOGGLE__VIEW__ACCORDION = 'TOGGLE__VIEW__ACCORDION';
export const SET__NEW__CHART = 'SET__NEW__CHART';